artifacts_root: artifacts

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/AjaykumarKothapally/AWS_Data_Engineering/refs/heads/main/data_coffee.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion